/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.schoolmng.school.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.exportimport.kernel.lar.StagedModelType;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;

import com.liferay.schoolmng.school.model.SchoolData;
import com.liferay.schoolmng.school.model.SchoolDataModel;
import com.liferay.schoolmng.school.model.SchoolDataSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the SchoolData service. Represents a row in the &quot;School&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link SchoolDataModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SchoolDataImpl}.
 * </p>
 *
 * @author Anjaneya
 * @see SchoolDataImpl
 * @see SchoolData
 * @see SchoolDataModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class SchoolDataModelImpl extends BaseModelImpl<SchoolData>
	implements SchoolDataModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a school data model instance should use the {@link SchoolData} interface instead.
	 */
	public static final String TABLE_NAME = "School";
	public static final Object[][] TABLE_COLUMNS = {
			{ "uuid_", Types.VARCHAR },
			{ "schoolId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "schoolName", Types.VARCHAR },
			{ "schoolType", Types.VARCHAR },
			{ "city", Types.VARCHAR },
			{ "noOfStudents", Types.INTEGER },
			{ "rating", Types.INTEGER },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("schoolId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("schoolName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("schoolType", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("city", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("noOfStudents", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("rating", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE = "create table School (uuid_ VARCHAR(75) null,schoolId LONG not null primary key,groupId LONG,schoolName VARCHAR(75) null,schoolType VARCHAR(75) null,city VARCHAR(75) null,noOfStudents INTEGER,rating INTEGER,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null)";
	public static final String TABLE_SQL_DROP = "drop table School";
	public static final String ORDER_BY_JPQL = " ORDER BY schoolData.schoolName ASC";
	public static final String ORDER_BY_SQL = " ORDER BY School.schoolName ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.schoolmng.school.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.com.liferay.schoolmng.school.model.SchoolData"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.schoolmng.school.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.com.liferay.schoolmng.school.model.SchoolData"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.schoolmng.school.service.util.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.liferay.schoolmng.school.model.SchoolData"),
			true);
	public static final long COMPANYID_COLUMN_BITMASK = 1L;
	public static final long GROUPID_COLUMN_BITMASK = 2L;
	public static final long UUID_COLUMN_BITMASK = 4L;
	public static final long SCHOOLNAME_COLUMN_BITMASK = 8L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static SchoolData toModel(SchoolDataSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		SchoolData model = new SchoolDataImpl();

		model.setUuid(soapModel.getUuid());
		model.setSchoolId(soapModel.getSchoolId());
		model.setGroupId(soapModel.getGroupId());
		model.setSchoolName(soapModel.getSchoolName());
		model.setSchoolType(soapModel.getSchoolType());
		model.setCity(soapModel.getCity());
		model.setNoOfStudents(soapModel.getNoOfStudents());
		model.setRating(soapModel.getRating());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<SchoolData> toModels(SchoolDataSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<SchoolData> models = new ArrayList<SchoolData>(soapModels.length);

		for (SchoolDataSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.schoolmng.school.service.util.ServiceProps.get(
				"lock.expiration.time.com.liferay.schoolmng.school.model.SchoolData"));

	public SchoolDataModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _schoolId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setSchoolId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _schoolId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return SchoolData.class;
	}

	@Override
	public String getModelClassName() {
		return SchoolData.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("uuid", getUuid());
		attributes.put("schoolId", getSchoolId());
		attributes.put("groupId", getGroupId());
		attributes.put("schoolName", getSchoolName());
		attributes.put("schoolType", getSchoolType());
		attributes.put("city", getCity());
		attributes.put("noOfStudents", getNoOfStudents());
		attributes.put("rating", getRating());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		String uuid = (String)attributes.get("uuid");

		if (uuid != null) {
			setUuid(uuid);
		}

		Long schoolId = (Long)attributes.get("schoolId");

		if (schoolId != null) {
			setSchoolId(schoolId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		String schoolName = (String)attributes.get("schoolName");

		if (schoolName != null) {
			setSchoolName(schoolName);
		}

		String schoolType = (String)attributes.get("schoolType");

		if (schoolType != null) {
			setSchoolType(schoolType);
		}

		String city = (String)attributes.get("city");

		if (city != null) {
			setCity(city);
		}

		Integer noOfStudents = (Integer)attributes.get("noOfStudents");

		if (noOfStudents != null) {
			setNoOfStudents(noOfStudents);
		}

		Integer rating = (Integer)attributes.get("rating");

		if (rating != null) {
			setRating(rating);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public long getSchoolId() {
		return _schoolId;
	}

	@Override
	public void setSchoolId(long schoolId) {
		_schoolId = schoolId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@JSON
	@Override
	public String getSchoolName() {
		if (_schoolName == null) {
			return "";
		}
		else {
			return _schoolName;
		}
	}

	@Override
	public void setSchoolName(String schoolName) {
		_columnBitmask = -1L;

		_schoolName = schoolName;
	}

	@JSON
	@Override
	public String getSchoolType() {
		if (_schoolType == null) {
			return "";
		}
		else {
			return _schoolType;
		}
	}

	@Override
	public void setSchoolType(String schoolType) {
		_schoolType = schoolType;
	}

	@JSON
	@Override
	public String getCity() {
		if (_city == null) {
			return "";
		}
		else {
			return _city;
		}
	}

	@Override
	public void setCity(String city) {
		_city = city;
	}

	@JSON
	@Override
	public int getNoOfStudents() {
		return _noOfStudents;
	}

	@Override
	public void setNoOfStudents(int noOfStudents) {
		_noOfStudents = noOfStudents;
	}

	@JSON
	@Override
	public int getRating() {
		return _rating;
	}

	@Override
	public void setRating(int rating) {
		_rating = rating;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(PortalUtil.getClassNameId(
				SchoolData.class.getName()));
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			SchoolData.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public SchoolData toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (SchoolData)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		SchoolDataImpl schoolDataImpl = new SchoolDataImpl();

		schoolDataImpl.setUuid(getUuid());
		schoolDataImpl.setSchoolId(getSchoolId());
		schoolDataImpl.setGroupId(getGroupId());
		schoolDataImpl.setSchoolName(getSchoolName());
		schoolDataImpl.setSchoolType(getSchoolType());
		schoolDataImpl.setCity(getCity());
		schoolDataImpl.setNoOfStudents(getNoOfStudents());
		schoolDataImpl.setRating(getRating());
		schoolDataImpl.setCompanyId(getCompanyId());
		schoolDataImpl.setUserId(getUserId());
		schoolDataImpl.setUserName(getUserName());
		schoolDataImpl.setCreateDate(getCreateDate());
		schoolDataImpl.setModifiedDate(getModifiedDate());

		schoolDataImpl.resetOriginalValues();

		return schoolDataImpl;
	}

	@Override
	public int compareTo(SchoolData schoolData) {
		int value = 0;

		value = getSchoolName().compareTo(schoolData.getSchoolName());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof SchoolData)) {
			return false;
		}

		SchoolData schoolData = (SchoolData)obj;

		long primaryKey = schoolData.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		SchoolDataModelImpl schoolDataModelImpl = this;

		schoolDataModelImpl._originalUuid = schoolDataModelImpl._uuid;

		schoolDataModelImpl._originalGroupId = schoolDataModelImpl._groupId;

		schoolDataModelImpl._setOriginalGroupId = false;

		schoolDataModelImpl._originalCompanyId = schoolDataModelImpl._companyId;

		schoolDataModelImpl._setOriginalCompanyId = false;

		schoolDataModelImpl._setModifiedDate = false;

		schoolDataModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<SchoolData> toCacheModel() {
		SchoolDataCacheModel schoolDataCacheModel = new SchoolDataCacheModel();

		schoolDataCacheModel.uuid = getUuid();

		String uuid = schoolDataCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			schoolDataCacheModel.uuid = null;
		}

		schoolDataCacheModel.schoolId = getSchoolId();

		schoolDataCacheModel.groupId = getGroupId();

		schoolDataCacheModel.schoolName = getSchoolName();

		String schoolName = schoolDataCacheModel.schoolName;

		if ((schoolName != null) && (schoolName.length() == 0)) {
			schoolDataCacheModel.schoolName = null;
		}

		schoolDataCacheModel.schoolType = getSchoolType();

		String schoolType = schoolDataCacheModel.schoolType;

		if ((schoolType != null) && (schoolType.length() == 0)) {
			schoolDataCacheModel.schoolType = null;
		}

		schoolDataCacheModel.city = getCity();

		String city = schoolDataCacheModel.city;

		if ((city != null) && (city.length() == 0)) {
			schoolDataCacheModel.city = null;
		}

		schoolDataCacheModel.noOfStudents = getNoOfStudents();

		schoolDataCacheModel.rating = getRating();

		schoolDataCacheModel.companyId = getCompanyId();

		schoolDataCacheModel.userId = getUserId();

		schoolDataCacheModel.userName = getUserName();

		String userName = schoolDataCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			schoolDataCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			schoolDataCacheModel.createDate = createDate.getTime();
		}
		else {
			schoolDataCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			schoolDataCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			schoolDataCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		return schoolDataCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(27);

		sb.append("{uuid=");
		sb.append(getUuid());
		sb.append(", schoolId=");
		sb.append(getSchoolId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", schoolName=");
		sb.append(getSchoolName());
		sb.append(", schoolType=");
		sb.append(getSchoolType());
		sb.append(", city=");
		sb.append(getCity());
		sb.append(", noOfStudents=");
		sb.append(getNoOfStudents());
		sb.append(", rating=");
		sb.append(getRating());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(43);

		sb.append("<model><model-name>");
		sb.append("com.liferay.schoolmng.school.model.SchoolData");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>uuid</column-name><column-value><![CDATA[");
		sb.append(getUuid());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>schoolId</column-name><column-value><![CDATA[");
		sb.append(getSchoolId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>schoolName</column-name><column-value><![CDATA[");
		sb.append(getSchoolName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>schoolType</column-name><column-value><![CDATA[");
		sb.append(getSchoolType());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>city</column-name><column-value><![CDATA[");
		sb.append(getCity());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>noOfStudents</column-name><column-value><![CDATA[");
		sb.append(getNoOfStudents());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>rating</column-name><column-value><![CDATA[");
		sb.append(getRating());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = SchoolData.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			SchoolData.class, ModelWrapper.class
		};
	private String _uuid;
	private String _originalUuid;
	private long _schoolId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private String _schoolName;
	private String _schoolType;
	private String _city;
	private int _noOfStudents;
	private int _rating;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _columnBitmask;
	private SchoolData _escapedModel;
}